### ISSUE TITLE
TI SensorTag CC2650 *AND* CC1350

### ISSUE THREAD

**Issue by scspaeth** [Staacks/phyphox-experiments#2]
The Phyphox device database page: https://phyphox.org/wiki/index.php?title=Bluetooth_device_database indicates:

> Note: The CC2650STK will be discontinued by TI and replaced by CC1350STK.

I ordered a pair of 2650s for our work but Digi-Key.com substituted 1350s. They arrived today and I am pleased to see that the Phyphox app recognizes them as an acceptable substitute for the '2650' experiments. Do you filter Bluetooth devices on the basis of Service Uuids and/or on partial-match names? If so, then you may want to remove references to the device numbers:

https://github.com/Staacks/phyphox-experiments/blob/2c58158aee348e397184b32e85150e69a3ecd7aa/bluetooth/TI%20CC2650%20SensorTag%20Accelerometer.phyphox#L3

**Comment by Staacks** [comment]
Correct, the experiment applies to both, the CC2650 and the CC1350, so "CC2650" should be removed from the category and the description should reference both.

In case of the SensorTag it is just a match of the name as defined by the name attribute in the bluetooth tag:
https://github.com/Staacks/phyphox-experiments/blob/2c58158aee348e397184b32e85150e69a3ecd7aa/bluetooth/TI%20CC2650%20SensorTag%20Accelerometer.phyphox#L17

So, this will also match any future BLE SensorTags (which might of course require changes in this configuration file). Alternatively, we can match advertised UUIDs like this:
https://github.com/Staacks/phyphox-experiments/blob/2c58158aee348e397184b32e85150e69a3ecd7aa/bluetooth/Heart%20Rate.phyphox#L13

But if I remember correctly, the SensorTag does not advertise its services.

**Comment by Staacks** [comment]
Fixed.
